## 2.1 数据操作  
1. 获取数据
2. 对数据进行处理    
**张量类**：支持自动微分

### 2.1.1 入门


In [2]:
# 导入pytorch
import torch
# 张量：
# 一个轴称：向量
# 两个轴  ：矩阵
# 两个以上：没有特殊名字，称为它的形状的张量

In [3]:
# 使用arange创建行向量
# 每个值称元素(element)
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
# 通过shape属性访问张量(沿每个轴的长度)的形状
x.shape

torch.Size([12])

In [5]:
# 只想知道张量元素总数
x.numel()

12

In [6]:
# 只改变张量形状
# 从形状（12,）的行向量转换为形状为（3,4）的矩阵。
X = x.reshape(3, 4)
X
# 可以通过-1调用自动计算出维度的功能
# = x.reshape(3, -1)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [7]:
# 使用全0，全1，其他常量，或者特定分布来初始化矩阵
# 创建形状为 (2, 3, 4) 的张量，元素为 0 
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [8]:
# 创建形状为 (2, 3, 4) 的张量，元素为 1
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [9]:
# 构造数组来作为神经网络中的参数时，通常会随机初始化参数的值
# 创建形状为(3, 4)的张量
# 每个元素都从均值为0、标准差为1的标准高斯分布（正态分布）中随机采样
torch.randn((3, 4))

tensor([[-1.7530,  0.0202, -0.7062,  0.6916],
        [ 1.2190, -1.6568,  0.6570,  0.1845],
        [ 0.3810, -1.7906,  0.0274,  0.7879]])

In [10]:
# 使用Python列表(或嵌套列表)为所需张量的每个元素赋值
# 最外层的列表对应于轴0，内层的列表对应于轴1
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

### 2.1.2 运算符  
在这些数据上执行数学运算


In [11]:
# 最简单且最有用的操作是按元素（elementwise）运算
# 对于任意具有相同形状的张量， 常见的标准算术运算符（+、-、*、/和**）都可以被升级为按元素运算。
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y  # **运算符是求幂运算

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [12]:
# “按元素”方式可以应用更多的计算包括求幂这样的一元运算符
torch.exp(x)
# 除了按元素计算外，我们还可以执行线性代数运算，包括向量点积和矩阵乘法

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [13]:
# 把多个张量连结（concatenate）在一起,叠起来形成一个更大的张量
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
X, Y, torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[2., 1., 4., 3.],
         [1., 2., 3., 4.],
         [4., 3., 2., 1.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [15]:
# 通过逻辑运算符构建二元张量
# 以X == Y为例
X == Y 

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [16]:
# 对张量中的所有元素进行求和，产生单元素张量
X.sum()

tensor(66.)

### 2.1.3 广播机制  
在某些情况下，即使形状不同，我们仍然可以通过调用 广播机制（broadcasting mechanism）来执行按元素操作。  
1. 通过适当复制元素来扩展一个或两个数组，以便在转换之后，两个张量具有相同的形状；
2. 对生成的数组执行按元素操作。

In [17]:
# 在大多数情况下，我们将沿着数组中长度为1的轴进行广播
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [18]:
# 矩阵a将复制列， 矩阵b将复制行，然后再按元素相加
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

### 2.1.4 索引和切片  
张量中的元素可以通过索引访问

In [19]:
# 我们可以用[-1]选择最后一个元素，用[1:3]选择第二个和第三个元素
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [20]:
# 通过指定索引来将元素写入矩阵
X[1, 2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [21]:
# 为多个元素赋值相同的值
# 索引所有元素，然后为它们赋值
# [0:2, :]访问第1行和第2行
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

### 2.1.5 节省内存  
例如，如果我们用Y = X + Y，我们将取消引用Y指向的张量，而是指向新分配的内存处的张量。

In [24]:
# 用Python的id()函数演示了这一点
before = id(Y)
Y = X + Y
id(Y) == before

False

In [25]:
# 节省内存！！！
# 1.在机器学习中，我们可能有数百兆的参数，在一秒内多次更新所有参数。
# 2.不原地更新，其他引用仍然会指向旧的内存位置，这样我们的某些代码可能会无意中引用旧的参数

# 使用切片表示法
Z = torch.zeros_like(Y)
print(f"idZ : {id(Z)}")
Z[:] = X + Y
print(f"idZ : {id(Z)}")

idZ : 2157446700304
idZ : 2157446700304


In [26]:
# 后续计算中没有重复使用X
# 可以使用X[:] = X + Y或X += Y来减少操作的内存开销。
before = id(X)
X += Y
id(X) == before

True

### 2.1.6 转换为其他的Python对象  
torch张量和numpy数组将共享它们的底层内存

In [27]:
# 就地操作更改一个张量也会同时更改另一个张量
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [28]:
# 将大小为1的张量转换为Python标量
# 调用item函数或Python的内置函数
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

### 2.1.7 小结  
深度学习存储和操作数据的主要接口是张量(n维数组)

### 2.1.8 练习

1. 运行本节中的代码。将本节中的条件语句X == Y更改为X < Y或X > Y，然后看看你可以得到什么样的张量。

In [29]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
X < Y, X > Y

(tensor([[ True, False,  True, False],
         [False, False, False, False],
         [False, False, False, False]]),
 tensor([[False, False, False, False],
         [ True,  True,  True,  True],
         [ True,  True,  True,  True]]))

2. 用其他形状（例如三维张量）替换广播机制中按元素操作的两个张量。结果是否与预期相同？

In [40]:
# 在大多数情况下，我们将沿着数组中长度为1的轴进行广播
a = torch.arange(6).reshape((1, 2, 3))
b = torch.arange(6).reshape((3, 2, 1))
a, b

(tensor([[[0, 1, 2],
          [3, 4, 5]]]),
 tensor([[[0],
          [1]],
 
         [[2],
          [3]],
 
         [[4],
          [5]]]))

In [41]:
# 沿着数组中长度为1的轴进行广播
a + b, (a+b).shape

(tensor([[[ 0,  1,  2],
          [ 4,  5,  6]],
 
         [[ 2,  3,  4],
          [ 6,  7,  8]],
 
         [[ 4,  5,  6],
          [ 8,  9, 10]]]),
 torch.Size([3, 2, 3]))